[listener]

  [listener.0]
    ip = '0.0.0.0'
    port = 53

  [listener.0.policy]
    name = "Split Horizon - greyrock.io to router"
    rules = [
        {"greyrock.io" = ["upstream.1"]},
        {"*.greyrock.io" = ["upstream.1"]},
    ]
    networks = [
        {"network.0" = ["upstream.0"]},
        {"network.1" = ["upstream.2"]},
        {"network.2" = ["upstream.3"]},
    ]

[network]

  [network.0]
    cidrs = ["10.1.10.0/24"]
    name = "Internal"

  [network.1]
    cidrs = ["10.1.0.0/24", "10.1.20.0/24"]
    name = "Minimal"

  [network.2]
    cidrs = ["192.168.23.0/24"]
    name = "Guest"

[upstream]

  [upstream.0]
    name = "Control D - Internal"
    type = "doh"
    endpoint = "https://dns.controld.com/5bj0g131ip"
    bootstrap_ip = "76.76.2.22"
    timeout = 5000

  [upstream.1]
    name = "Internal Router"
    type = "legacy"
    endpoint = "10.1.30.1:53"
    timeout = 3000

  [upstream.2]
    name = "Control D - Minimal"
    type = "doh"
    endpoint = "https://dns.controld.com/18omwwxv3la"
    bootstrap_ip = "76.76.2.22"
    timeout = 5000

  [upstream.3]
    name = "Control D - Guest"
    type = "doh"
    endpoint = "https://dns.controld.com/dihmae97cq"
    bootstrap_ip = "76.76.2.22"
    timeout = 5000
